networks:
  gateway:
    external: true

volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: kvdomingo/go-tracker-api:latest
    env_file: .env
    volumes:
      - .:/backend
    depends_on:
      - redis

  frontend:
    image: node:16-alpine
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
      - WDS_SOCKET_PORT=0
    working_dir: /web
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn start"
    volumes:
      - ./web/app:/web

  redis:
    image: redis/redis-stack:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotracker-redisinsight-dev.rule=Host(`redisinsight.go-tracker-dev.localhost`)"
      - "traefik.http.routers.gotracker-redisinsight-dev.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.gotracker-redisinsight-dev.loadbalancer.server.port=8001"
    volumes:
      - db-data:/data
    networks:
      - default
      - gateway

  proxy:
    image: bitnami/nginx:latest
    volumes:
      - ./proxy/dev:/opt/bitnami/nginx/conf/server_blocks:ro
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotracker-dev.rule=Host(`go-tracker-dev.localhost`)"
      - "traefik.http.routers.gotracker-dev.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.gotracker-dev.loadbalancer.server.port=8000"
    networks:
      - default
      - gateway
    restart: unless-stopped
