services:
  api:
    build: .
    image: kvdomingo/go-tracker-api
    init: true
    env_file: .env
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  ui:
    image: oven/bun:1.1
    environment:
      NODE_ENV: development
    working_dir: /web
    init: true
    command:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    volumes:
      - ./ui:/web

  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
    volumes:
      - db-data:/data

  postgres:
    image: bitnami/postgresql:16.2.0-debian-12-r17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami/postgresql

volumes:
  db-data:
  postgres-data:
