version: '3'

vars:
  NAME: go-tracker-dev

dotenv:
  - .env

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name {{.NAME}} up -d --build --remove-orphans {{.CLI_ARGS}}

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.NAME}} exec {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.NAME}} down -v --remove-orphans {{.CLI_ARGS}}

  makemigrations:
    desc: Create database migrations
    dir: api
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate:
    desc: Apply database migrations
    dir: api
    cmds:
      - migrate -source file://migrations -database pgx5://{{.POSTGRESQL_USERNAME}}:{{.POSTGRESQL_PASSWORD}}@localhost:5432/{{.POSTGRESQL_DATABASE}}?sslmode=disable up

  psql:
    desc: Connect to PostgreSQL
    cmds:
      - task exec -- -it postgres psql -U {{.POSTGRESQL_USERNAME}} -d {{.POSTGRESQL_DATABASE}}
